name: fuel_app
description: Aplikacja do śledzenia zużycia paliwa (LPG i PB) z funkcją OCR.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Wybór plików i plików graficznych
  file_picker: ^8.1.2
  image_picker: ^1.1.2

  # OCR i przetwarzanie tekstu
  google_mlkit_text_recognition: ^0.13.0

  # Obsługa plików Excel, ścieżek i udostępniania
  excel: 2.1.0  # Zablokowana wersja 2.1.0 unikająca konfliktów z klasami Fluttera
  path_provider: ^2.1.5
  share_plus: ^10.0.0

  # Przechowywanie preferencji i kopii zapasowych
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
