name: fuel_app
description: Aplikacja do śledzenia zużycia paliwa (LPG i PB) z funkcją OCR.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # Integracja mowy i plików
  speech_to_text: ^7.3.0
  file_picker: ^8.0.0
  path_provider: ^2.1.2
  share_plus: ^8.0.2
  shared_preferences: ^2.2.2

  # OCR i multimedia
  image_picker: ^1.0.7
  google_mlkit_text_recognition: ^0.11.0

  # Eksport danych
  excel: 2.1.0 # Zablokowana wersja unika konfliktów typów z Flutterem

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
