name: fuel_tracker
description: Aplikacja do śledzenia zużycia kosztów paliwa (PB i LPG) z funkcją OCR.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.0

  image_picker: ^1.0.7
  google_mlkit_text_recognition: ^0.11.0
  excel: 2.1.0  # Zablokowana wersja 2.1.0 unikająca konfliktów z klasami Fluttera
  path_provider: ^2.1.2
  share_plus: ^8.0.2
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2  # Dodane do śledzenia daty ostatniego backupu (miesięczny automatyczny backup)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
